[[tasks]]
id = "test-task-1"
dependencies = []

env = []
command = "ls"
arguments = ["-1"]
working_dir = "./target"


[[tasks]]
id = "test-task-3"
dependencies = []

env = []
command = "sleep"
arguments = ["5"]
working_dir = "./"
